### ISSUE TITLE
Getting no attribute COAP when trying to add a shelly device

### ISSUE THREAD

**Issue by Jeltel** [bieniu/ha-shelly-own-coap#1]
* Copied the files over to \config\custom_components\shelly and restarted.
* Via the integrations tried to add a shelly devices via IP address.
* after pressing enter getting an unexpected error:
![afbeelding](https://user-images.githubusercontent.com/1732436/97542653-6c3c2780-19c7-11eb-8bbb-6c2c70f8d18d.png)

* In the log this error occurs:
```
Traceback (most recent call last):
  File "/config/custom_components/shelly/config_flow.py", line 90, in async_step_user
    device_info = await validate_input(self.hass, self.host, {})
  File "/config/custom_components/shelly/config_flow.py", line 44, in validate_input
    await get_coap_context(hass)
  File "/config/custom_components/shelly/__init__.py", line 32, in get_coap_context
    hass.data[DOMAIN][COAP_CONTEXT] = aioshelly.COAP()
AttributeError: module 'aioshelly' has no attribute 'COAP'
```

**Comment by bieniu** [comment]
Ops, you have old `aioshelly`. Please wait a minute.

**Comment by bieniu** [comment]
Please update `manifest.json` file https://github.com/bieniu/ha-shelly-own-coap/blob/master/custom_components/shelly/manifest.json
